### ISSUE TITLE
AttributeError: module 'riotgen' has no attribute 'main'

### ISSUE THREAD

**Issue by mzew** [aabadie/riot-generator#13] opened 2021-02-11 11:12 UTC
Hello,
I have freshly installed Manjaro with zsh and Python 3.9.1. Installed riotgen using pip. When riotgen is called, I constantly get the following error:

`Traceback (most recent call last):
  File "/home/ym/.local/bin/riotgen", line 33, in <module>
    sys.exit(load_entry_point('riotgen==0.7.1', 'console_scripts', 'riotgen')())
  File "/home/ym/.local/bin/riotgen", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'riotgen' has no attribute 'main'`

**Comment by aabadie** [comment] 2021-02-11 11:19
The [latest run on th CI](https://github.com/aabadie/riot-generator/actions/runs/557124122) is now also testing on Python 3.9.1 on Ubuntu, MacOS and Windows and it works (there's a check that verifies `riotgen --help` is working).

What is your version of pip ? I'm using 21.0.1.

**Comment by mzew** [comment] 2021-02-11 11:28
pip 20.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)

**Comment by aabadie** [comment] 2021-02-11 11:46
I know people using Arch has the same problem but I don't use Arch and I'm not able to easily reproduce the issue.

**Comment by mzew** [comment] 2021-03-08 22:15
Update: The issue is somewhere in launcher or probably a way pip installs the package:
in Ubuntu:
`#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from riotgen import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main.riotgen())`

in Manjaro:
`#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'riotgen==0.7.1','console_scripts','riotgen'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'riotgen==0.7.1'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('riotgen==0.7.1', 'console_scripts', 'riotgen')())`

**Comment by mzew** [comment] 2021-03-08 22:37
Yes, 'from riotgen import main' is missing in Manjaro. Added manually, works. However that's a hack

**Comment by Shikoruma** [comment] 2021-03-24 10:45
I had the same issue. I resolved it by installing the package wheel before installing riotgen.
I think the legacy install not working.

Using legacy 'setup.py install' for riotgen, since package 'wheel' is not installed

**Comment by aabadie** [comment] 2021-04-03 13:41
> I resolved it by installing the package wheel before installing riotgen.

Thanks for pointing that, the wheel was indeed not published on pypi and now this is the case (see b604deea5ad95409c6c5ecdfb69fde4c2d701aa7).

@mzew, do you confirm that you don't have the issue anymore after updating the package to 0.8.3 ?

**Comment by aabadie** [comment] 2021-04-13 11:56
Someone in RIOT confirmed me that it now works on Arch. I'm closing this issue since it's now fixed. Feel free to re-open if you disagree.

**Closed by aabadie** 2021-04-13 11:56 UTC

**Comment by mzew** [comment] 2021-04-13 12:05
I confirm, the issue was fixed. Thanks!
